### ISSUE TITLE
HomuraMC ToDo [rewrite]

### ISSUE THREAD

**Issue by nennneko5787** [HomuraMC/Homura#1]
## High
- [x] YAML Config / コンフィグ(yaml)
## Medium
- [ ] Plugin API / プラグインAPI
## Low
- [ ] Custom server list ping / カスタマイズできるサーバーリスト表示
- [ ] Tab list / タブリスト
- [ ] Sending chunks / チャンクの送信
- [ ] Mob AI / モブのAI
- [ ] Tab complete / Tab補完
- [ ] Minecraft commands / Minecraftのコマンド
- [ ] Command block / コマンドブロック
- [ ] Bedrock support / 統合版のサポート

**Comment by sonyakun** [comment]
* [ ]  Custom server list ping / カスタマイズできるサーバーリスト表示
* [ ]  Tab list / タブリスト
* [ ]  Correct skin of the player / プレイヤーの正しいスキン
* [x]  Sending chunks / チャンクの送信 (多分低速)
* [ ]  Mob AI / モブのAI
* [ ]  Tab complete / Tab補完
* [ ]  Minecraft commands / Minecraftのコマンド
* [ ]  Command block / コマンドブロック
* [x]  Plugin loader / プラグインローダー

今はこんな感じかな?

**Comment by nennneko5787** [comment]
- [ ] Replace config to yml from ini / 設定ファイルをiniからymlに変える
追加した

**Comment by nennneko5787** [comment]
増やした

**Comment by nennneko5787** [comment]
- [ ] Tab list / タブリスト
についてですが、これに関連する変更が行われましたが、対応できたことを確認していません
まだチェックはつけないままにしておきます

**Comment by nennneko5787** [comment]
- [ ] Custom server list ping / カスタマイズできるサーバーリスト表示
これも少し怪しいかも
サーバーアイコンがおかしいかも
誰か検証してくださいな

**Comment by nennneko5787** [comment]
- [ ] Bedrock support / 統合版のサポート
は[https://github.com/SpockBotMC/python-minecraft-data](https://github.com/SpockBotMC/python-minecraft-data)を3.33.0に対応させればおｋ

**Comment by nennneko5787** [comment]
- [ ] Support all versions of minecraft / Minecraftのどのバージョンもサポート
実はできてない

**Comment by sonyakun** [comment]
プラグインAPIの懸念点
* ユーザーの情報にアクセスして何らかの方法で情報を送信できる
* 上記の方法で仮にDiscordやMisskeyなどのAPIトークンなどが記載されたファイルがあった場合にそのトークンを利用するBotが一時的に乗っ取られる可能性がある
etc...

これの懸念をどうにかして払しょくする必要はありそう

(related by [Offical Discord](https://discord.com/channels/1141329766889300070/1141329767858196522/1184114689962168330))

**Comment by sonyakun** [comment]
> Bedrock support / 統合版のサポート
はhttps://github.com/SpockBotMC/python-minecraft-dataを3.33.0に対応させればおｋ


ちなみにこれはどういうこと？

**Comment by nennneko5787** [comment]
> > Bedrock support / 統合版のサポート
> > は[https://github.com/SpockBotMC/python-minecraft-dataを3.33.0に対応させればおｋ](https://github.com/SpockBotMC/python-minecraft-data%E3%82%923.33.0%E3%81%AB%E5%AF%BE%E5%BF%9C%E3%81%95%E3%81%9B%E3%82%8C%E3%81%B0%E3%81%8A%EF%BD%8B)
> 
> ちなみにこれはどういうこと？

minecraft-dataっていうやつをpythonに対応したやつが古いから新しくしなきゃいけないってこと
https://github.com/SpockBotMC/python-minecraft-data

**Comment by sonyakun** [comment]
> > > Bedrock support / 統合版のサポート
> > > は[https://github.com/SpockBotMC/python-minecraft-dataを3.33.0に対応させればおｋ](https://github.com/SpockBotMC/python-minecraft-data%E3%82%923.33.0%E3%81%AB%E5%AF%BE%E5%BF%9C%E3%81%95%E3%81%9B%E3%82%8C%E3%81%B0%E3%81%8A%EF%BD%8B)
> > 
> > 
> > ちなみにこれはどういうこと？
> 
> minecraft-dataっていうやつをpythonに対応したやつが古いから新しくしなきゃいけないってこと https://github.com/SpockBotMC/python-minecraft-data

Homura関係だから、HomuraMC組織でそれフォークできない？(所有者は別に誰でもいいから任意で)見た感じsubmodulesでminecraft-dataがリンクされてるから更新すれば最新のやつにできる

**Comment by nennneko5787** [comment]
> > > > Bedrock support / 統合版のサポート
> 
> > > > は[https://github.com/SpockBotMC/python-minecraft-dataを3.33.0に対応させればおｋ](https://github.com/SpockBotMC/python-minecraft-data%E3%82%923.33.0%E3%81%AB%E5%AF%BE%E5%BF%9C%E3%81%95%E3%81%9B%E3%82%8C%E3%81%B0%E3%81%8A%EF%BD%8B)
> 
> > > 
> 
> > > 
> 
> > > ちなみにこれはどういうこと？
> 
> > 
> 
> > minecraft-dataっていうやつをpythonに対応したやつが古いから新しくしなきゃいけないってこと https://github.com/SpockBotMC/python-minecraft-data
> 
> 
> 
> Homura関係だから、HomuraMC組織でそいつフォークできない？(所有者は別に誰でもいいから任意で)見た感じsubmodulesでminecraft-dataがリンクされてるから更新すれば最新のやつにできる

やりたいけど、iOSからフォークできない
朝になったらやります

**Comment by sonyakun** [comment]
> > > > > Bedrock support / 統合版のサポート
> > 
> > 
> > > > > は[https://github.com/SpockBotMC/python-minecraft-dataを3.33.0に対応させればおｋ](https://github.com/SpockBotMC/python-minecraft-data%E3%82%923.33.0%E3%81%AB%E5%AF%BE%E5%BF%9C%E3%81%95%E3%81%9B%E3%82%8C%E3%81%B0%E3%81%8A%EF%BD%8B)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ちなみにこれはどういうこと？
> > 
> > 
> > > 
> > 
> > 
> > > minecraft-dataっていうやつをpythonに対応したやつが古いから新しくしなきゃいけないってこと https://github.com/SpockBotMC/python-minecraft-data
> > 
> > 
> > Homura関係だから、HomuraMC組織でそいつフォークできない？(所有者は別に誰でもいいから任意で)見た感じsubmodulesでminecraft-dataがリンクされてるから更新すれば最新のやつにできる
> 
> やりたいけど、iOSからフォークできない 朝になったらやります

ok

**Comment by nennneko5787** [comment]
- [ ] Plugin API / プラグインAPI
ついか

**Comment by nennneko5787** [comment]
やっとHomuraMCに対するモチベーションが上がった
明日から作業しまくります

**Comment by nennneko5787** [comment]
リライト版なんでふりだしに戻ります

**Comment by sonyakun** [comment]
がんばろ

**Comment by sonyakun** [comment]
> * [ ]  Replace config to yml from ini / 設定ファイルをiniからymlに変える
>   追加した

とりあえずこれは#10 で完了するね

**Comment by nennneko5787** [comment]
そうやね
